apiVersion: v1
kind: ConfigMap
metadata:
  name: zap-advanced-scan-config
data:
  2-zap-advanced-scan.yaml: |-

    # ZAP Contexts Configuration 
    contexts:
      - name: scb-onlineboutique-context
        url: http://frontend.default.svc:80/
        includePaths:
          - "http://frontend.default.svc:80.*"
        excludePaths:
          - ".*socket\\.io.*"
          - ".*\\.png"
          - ".*\\.jpeg"
          - ".*\\.jpg"
          - ".*\\.woff"
          - ".*\\.woff2"
          - ".*\\.ttf"
          - ".*\\.ico"

    # ZAP Spiders Configuration 
    spiders:
      - name: scb-onlineboutique-spider
        context: scb-onlineboutique-context
        url: http://frontend.default.svc:80/
        ajax: true
        failIfFoundUrlsLessThan: 0
        warnIfFoundUrlsLessThan: 0
        maxDuration: 5
        maxDepth: 10

    # ZAP ActiveScans Configuration 
    scanners:
      - name: scb-onlineboutique-scan
        context: scb-onlineboutique-context
        url: http://frontend.default.svc:80/
        maxRuleDurationInMins: 1
        maxScanDurationInMins: 10
        threadPerHost: 5
        delayInMs: 0
        addQueryParam: false
        handleAntiCSRFTokens: true
        injectPluginIdInHeader: false
        scanHeadersAllRequests: true

---
apiVersion: "execution.securecodebox.io/v1"
kind: Scan
metadata:
  name: "zap-authenticated-full-scan-onlineboutique"
  labels:
    organization: "googlecloud"
spec:
  scanType: "zap-advanced-scan"
  parameters:
    - "-t"
    - "http://frontend.default.svc:80/"
  volumeMounts:
    - name: zap-advanced-scan-config
      mountPath: /home/securecodebox/configs/2-zap-advanced-scan.yaml
      subPath: 2-zap-advanced-scan.yaml
      readOnly: true
  volumes:
    - name: zap-advanced-scan-config
      configMap:
        name: zap-advanced-scan-config
